# Generated by Django 2.2.3 on 2020-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.FileField(max_length=1000, upload_to='media/'),
        ),
    ]
